//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineJewelleryShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartMaster
    {
        public int Id { get; set; }
        public Nullable<int> PId { get; set; }
        public Nullable<int> Uid { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
