//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineJewelleryShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class JewelleryMaster
    {
        public int Id { get; set; }
        public string JewelleryName { get; set; }
        public Nullable<int> JewelleryType { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> JewelleryCategory { get; set; }
        public string JewelleryImage { get; set; }
    }
}
